# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: C4Coffee
email: yuanv@alumni.ubc.ca
description: > # this means to ignore newlines until "baseurl:"
 >Engineer. Robots. Coffee.
 >80/20 Pareto Engineering
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://c4coffee.ca" # the base hostname & protocol for your site
github_username: Dulluhan

gems:
 - jekyll-sitemap

# Build settings
markdown: kramdown
  # gem:[archivegenerator, monthly_archive_plugin, category_archive_plugin, sitemap_generator]

#sitemap settings
sitemap:file: "../sitemap.xml"
excerpt_seperator: "<!--more-->"
