---
title: C is For Coffee
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: yuanv@alumni.ubc.ca
baseurl: ''
url: http://c4coffee.ca
github_username: Dulluhan
linkedin_username: vincentyuan
gems:
- jekyll-sitemap
- jekyll-redirect-from
- jekyll-seo-tag
- jekyll-feed
markdown: kramdown
highlighter: rouge
sitemap:file: "../sitemap.xml"
excerpt_seperator: "<!--more-->"
include:
- _pages
